config/routes.rb
Rails.application.routes.draw do
  delete '/logout', to: 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#auth_failure'
  get '/admin-login', to: 'sessions#new'
  post '/admin-login', to: 'sessions#create_standard'
  get '/admin-logout', to: 'sessions#delete'
  delete "/admin-logout", to: "sessions#destroy"

  namespace :admin do
    get 'imports/import'
  end

  get '/sitemap.xml.gz', to: redirect("https://#{ENV['S3_BUCKET_NAME']}.s3.amazonaws.com/sitemaps/sitemap.xml.gz"), as: :sitemap
  root "welcome#index"

  get '/credit-card-beginners-guide', to: 'pages#start_here'
  get '/what-is-a-credit-score', to: 'pages#what_is_a_credit_score'
  get '/types-of-credit-cards', to: 'pages#types_of_credit_cards'
  get '/the-credit-card-game', to: 'pages#the_credit_card_game'

  resources :about, only: [:index]
  resources :users, only: [:show, :update, :edit, :destroy]
  resources :cards, only: [:index, :show]
  resources :blogs, only: [:index, :show]

  resources :categories, only: [:index]
  get "categories/:id", to: redirect("/%{id}")
  resources :categories, path: "", only: [:show]

  namespace :admin do
    get 'imports/index'
    resources :cards, only: [:new, :create, :edit, :update, :index]
    resources :rewards, only: [:new, :create, :edit, :update, :index, :destroy]
    resources :blogs
    resources :main_programs
    resources :card_programs
    resources :transfer_partners
    resources :imports do
      collection { post :import}
    end
  end

  namespace :api do
    namespace :v1, defaults: {format: :json} do
      get "/search", to: 'auto_complete#search'
      resources :rewards, only: [:show]
      get "/reward/:id", to: 'rewards#show_one'
      resources :categories, only: [:show]
      resources :favorite_cards
      resources :users, only: [:show]
      resources :cards, only: [:index]
      get 'card_names', to: 'cards#card_names'
      resources :blogs, only: [:index, :show]
      resources :related_blogs, only: [:show]
      resources :recent_blogs, only: [:index]
      resources :transfer_partners, only: [:show]
      get "/show_related_blogs/:id", to: "related_blogs#show_related_blogs"
    end
  end
end

app/models/card.rb
class Card < ActiveRecord::Base
  has_many :rewards

  has_many :categorizings
  has_many :categories, through: :categorizings

  has_many :favorite_cards
  has_many :users, through: :favorite_cards

  has_many :card_blogs
  has_many :blogs, through: :card_blogs

  has_many :card_program_transfer_partners
  has_many :transfer_partners, through: :card_program_transfer_partners

  belongs_to :card_program, class_name: "CardProgram"
  belongs_to :main_program, class_name: "MainProgram"

  accepts_nested_attributes_for :categories,
                                  reject_if: :all_blank,
                                  allow_destroy: true

  validates :name,
              presence: true
  validates :annual_fee,
              presence: true
  validates :apr,
              presence: true
  validates :intro_rate,
              presence: true
  validates :image_link,
              presence: true

  self.per_page = 10

  scope :find_cards_that_are_in_multiple_categories, ->(category_names) { where(id: Card.cards_with_multiple_categories(category_names)) }
  scope :exclude_cash_and_other_cards, -> { joins(:categories).where.not({categories: {id: [5,6]}}) }
  scope :name_like, ->(params) { where("cards.name LIKE ?", "%#{params}%") }

  def self.cards_with_multiple_categories(category_names)
    joins(:categories)
    .where('categories.name' => category_names)
    .group(:id)
    .having('count(categories.name) >= ?', category_names.length)
  end

  def parse_card_categories_name
    name = self.categories.map do |category|
      category.name.gsub("-", " ").titleize
    end
  end

  def self.search(params)
    exclude_cash_and_other_cards.name_like(params).uniq
  end

  def self.card_names
    exclude_cash_and_other_cards.pluck(:id, :name).uniq
  end
end

app/controllers/admin/cards_controller.rb
class Admin::CardsController < Admin::BaseController
  before_action :load_card, only: [:show, :edit, :update, :destroy]
  before_action :load_presenter, only: [:edit, :update]
  before_filter :format_card_information, only: [:create, :update]
  before_action :no_index_no_follow, only: [:index, :new, :edit]

  def index
    no_index_no_follow
    @cards = Card.all
    @users = User.all
  end

  def show
  end

  def new
    @card = Card.new
  end

  def create
    selected_categories   = card_params[:categories]
    selected_card_program = card_params[:card_program]
    elected_main_card_program = card_params[:main_program]
    @card = Card.new(card_params.except(:categories, :card_program, :main_program))
    if @card.save
      assign_categories_to_card(selected_categories)
      assign_card_program_to_card(selected_card_program)
      assign_card_program_to_card(selected_card_program)
      flash[:success] = "Card successfully added!"
      redirect_to admin_cards_path
    else
      flash.now[:errors] = @card.errors.full_messages.join(", ")
      render :new
    end
  end

  def edit
    @card.categories.build
  end

  def update
    selected_categories        = card_params[:categories]
    selected_card_program      = card_params[:card_program]
    selected_main_card_program = card_params[:main_program]
    if @card.update(card_params.except(:categories, :card_program, :main_program))
      assign_categories_to_card(selected_categories)
      assign_main_card_program_to_card(selected_main_card_program)
      assign_card_program_to_card(selected_card_program)
      flash[:success] = "Card successfully updated!"
      redirect_to edit_admin_card_path(@card)
    else
      flash.now[:errors] = @card.errors.full_messages.join(", ")
      render :edit
    end
  end

  def destroy
    @card.delete
    redirect_to admin_cards_path
  end

  private

    def load_card
      @card = Card.find(params[:id])
    end

    def load_presenter
      @card_rewards = CardPresenter.new(@card.id)
    end

    def format_card_information
      convert_form_information_to_sentences(params)
    end

    def convert_form_information_to_sentences(params)
      split_params                = params[:card][:information].split(". ")
      last_element_formatted      = split_params[-1].gsub(".", "")
      split_params.pop
      formatted_information       = split_params.insert(-1, last_element_formatted)
      params[:card][:information] = formatted_information.map! {|info| "#{info}." }
    end

    def assign_categories_to_card(selected_categories)
      selected_categories.each do |id|
        if ((id != "") and (card_not_already_assigned(id) == false))
          category = Category.find(id)
          @card.categories << category
        end
      end
    end

    def assign_main_card_program_to_card(selected_main_card_program)
      if selected_main_card_program.length > 1 && selected_main_card_program[0] == ""
        @card.update(main_program_id: MainProgram.find(selected_main_card_program[-1]).id)
      end
    end


    def assign_card_program_to_card(selected_card_program)
      if @card.card_program === nil

        selected_card_program.each do |id|
          if id != ""
            @card.update(card_program_id: CardProgram.find(id).id)
          end
        end

      else

        selected_card_program.each do |id|
          if id != "" && card_not_already_assigned_card_program(id)
            @card.update(card_program_id: CardProgram.find(id).id)
          end
        end

      end
    end

    def card_not_already_assigned(id)
      @card.categories.include?(Category.find(id))
    end

    def card_not_already_assigned_card_program(id)
      @card.card_program != CardProgram.find(id)
    end

    def card_params
      params.require(:card).permit(:name,
                                   :annual_fee,
                                   :apr,
                                   :intro_rate,
                                   :image_link,
                                   :best_offer,
                                   :flyer_talk_link,
                                   :image_url,
                                   :point_type,
                                   :credit_score,
                                   :bus_card,
                                   :has_fee,
                                   :categories => [],
                                   :main_program => [],
                                   :card_program => [],
                                   :information => [])
    end
end

app/controllers/api/v1/cards_controller.rb
class Api::V1::CardsController < ApplicationController
  respond_to :json
  before_action :set_cache_headers!, only: [:index]

  def index
    if search_params[:search]
      cards = Card.search(search_params[:search]).order("created_at DESC")
      render json: cards,
                    adapter: :json, each_serializer: Api::V1::SearchSerializer,
                    meta: { favorite_card_ids: current_user_favorite_ids, search_term: search_params[:search] }
    else
      cards = []
      render json: cards,
                    adapter: :json, each_serializer: Api::V1::SearchSerializer,
                    meta: { favorite_card_ids: current_user_favorite_ids, search_term: "blank" }
    end
  end

  def card_names
    cards = Card.card_names
    respond_with cards
  end

  private

  def search_params
    params.permit(:search)
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  def index
    format_search_term(params)
    if params[:search]
      @card_count= Card.search(params[:search]).count
    else
      @card_count = Card.all.order('created_at DESC')
    end
  end

  def show
    @card_presenter          = CardPresenter.new(params[:id])
    @featured_card_presenter = FeaturedCardPresenter.new(params[:id])
  end

  private

    def format_search_term(params)
      if params[:search] != ""
        @search_term = "=" + params[:search]
      else
        @search_term = nil
      end
    end
end

app/views/admin/cards/_edit_form.html.erb
<%= bootstrap_form_for([:admin, @card]) do |card_form| %>
  <%= card_form.text_field :name %>
  <%= card_form.text_field :annual_fee %>
  <%= card_form.text_field :apr %>
  <%= card_form.text_field :intro_rate %>
  <%= card_form.text_field :image_link %>
  <h3>Card Categories</h3>
  <div id='categories'>
    <%= card_form.fields_for :categories do |categories_fields| %>
      <%= categories_fields.text_field :name %>
      <%= categories_fields.text_field :slug %>
      <%= categories_fields.check_box :_destroy %>
      <%= categories_fields.label :_destroy, 'remove' %>
    <% end %>
  </div>
  <%= card_form.submit 'Update Card' %>
<% end %>

app/views/admin/cards/_form.html.erb
<%= bootstrap_form_for([:admin, @card]) do |card_form| %>
  <%= card_form.text_field :name %>
  <%= card_form.text_field :annual_fee %>
  <%= card_form.text_field :apr %>
  <%= card_form.text_field :intro_rate %>
  <%= card_form.text_field :image_link %>
  <%= card_form.text_field :information %>
  <%= card_form.text_field :best_offer %>
  <%= card_form.text_field :flyer_talk_link %>
  <%= card_form.text_field :image_url %>
  <%= card_form.text_field :point_type %>
  <%= card_form.text_field :credit_score %>
  <%= card_form.check_box :bus_card %>
  <%= card_form.check_box :has_fee %>
  <%= card_form.collection_select :categories, Category.order(:name),:id,:name, {:include_blank => true}, {:multiple => true} %>
  <%= card_form.collection_select :main_program, MainProgram.order(:name),:id,:name, {:include_blank => false}, {:multiple => true} %>
  <%= card_form.collection_select :card_program, CardProgram.order(:name),:id,:name, {:include_blank => false}, {:multiple => true} %>
  <%= card_form.submit 'Submit Information' %>
<% end %>

app/views/admin/cards/_new_card_form.erb
<%= bootstrap_form_for([:admin, @card]) do |card_form| %>
  <%= card_form.text_field :name %>
  <%= card_form.text_field :annual_fee %>
  <%= card_form.text_field :apr %>
  <%= card_form.text_field :intro_rate %>
  <%= card_form.text_field :image_link %>
  <h3>Card Categories</h3>
  <div id='categories'>
    <%= card_form.fields_for :categories do |categories_fields| %>
      <%= categories_fields.text_field :name %>
      <%= categories_fields.text_field :slug %>
      <%= categories_fields.check_box :_destroy %>
      <%= categories_fields.label :_destroy, 'remove' %>
    <% end %>
  </div>
  <%= card_form.submit 'Add New Card' %>
<% end %>

app/views/admin/cards/edit.html.erb
<% provide(:title, "Admin - Edit Card") %>
 <div class="container">
 <br><br>
    <h1><%= link_to "See All Cards", admin_cards_path %></h1>
    <div class="row well">
      <div class="col-lg-12">
        <div class="card-details">
          <h2>Card Details</h2>
          <%= render partial: 'form' %>
        </div><br>
        <h3>Card Rewards</h3>
        <%= link_to "Add Another Reward for #{@card.name} ", {:controller => "rewards", :action => "new", :id => @card.id } %>
        <% if @card_rewards.rewards.any? %>
          <table class='table table-bordered reward-table' id='rewards'>
            <tr>
              <th></th>
              <th>Record Date</th>
              <th>Reward Amount (Points/Miles)</th>
              <th>Required Spending Amount</th>
              <th>Length of Time (Months)</th>
              <th>Apply Link </th>
            </tr>
            <tr>
            <% @card_rewards.rewards.each do |reward| %>
              <td><%= link_to "Edit", edit_admin_reward_path(reward) %> | <%= link_to "Delete", admin_reward_path(reward), method: :delete, data: {confirm: "Are you sure you want to delete this reward"} %> </td>
              <td><%= reward.record_date %></td>
              <td><%= reward.amount %></td>
              <td><%= number_to_currency(reward.spending_amount, precision: 0) %></td>
              <td><%= reward.length_of_time %></td>
              <td><%= reward.apply_link %></td>
            </tr>
            <% end %>
          </table>
      <% else %>
        <h5>This card has no rewards!</h5>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/cards/index.html.erb
<% provide(:title, "Admin Panel") %>
<br>
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h3><%= link_to "See Admin Blog", admin_blogs_path %></h3>
      <br>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h3><%= link_to "Update Main Programs", admin_main_programs_path %></h3>
      <br>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h3><%= link_to "Update Card Program Transfer Partners", admin_card_programs_path %></h3>
      <br>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h3><%= link_to "Update Transfer Partners", admin_transfer_partners_path %></h3>
      <br>
    </div>
  </div>
</div>
<div class="container upload-file">
  <div class="row">
    <div class="col-lg-12">
      <h3>Import a CSV File from Reddit</h3>
      <%= form_tag import_admin_imports_path, multipart: true do %>
        <%= file_field_tag :file %>
        <%= date_field_tag :date %>
        <%= submit_tag "Import CSV" %>
      <% end %>
      <br>
    </div>
  </div>
</div>
<br>
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h3>Enter Site for Point Valuations</h3>
      <%= form_tag import_admin_imports_path, multipart: true do %>
        <%= url_field_tag :url %><br>
        <%= month_field_tag :month %>
        <%= submit_tag "Digest Site" %>
      <% end %>
      <br>
      <li><%= link_to "Add New Card", new_admin_card_path %></li>
      <li><%= link_to "Logout", admin_logout_path, method: :delete %></li>
    </div>
  </div>
</div>
<br>
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header"> Admin - All Cards</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-md-7 card-list">
      <% @cards.each do |card| %>
      <div id="card-<%= card.id %>">
        <%= card.name %> | <%= link_to 'Edit', edit_admin_card_path(card) %> | <%= link_to 'Show', card_path(card) %> | <%= card.parse_card_categories_name %>
        <hr>
      </div>
      <% end %>
    </div>
  </div>
<br><br>

<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header"> Admin - All Users</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-md-7 card-list">
      <% @users.each do |user| %>
      <div>
        <%= user.name %>
        <hr>
      </div>
      <% end %>
    </div>
  </div>
<br><br>

app/views/admin/cards/new.html.erb
<% provide(:title, "Admin - Add Card") %>
<div class="container">
  <div class="row well">
    <div class="col-lg-12">
      <h2>Add a New Card</h2>
      <%= render partial: 'form' %>
    </div>
  </div>
</div>