config/routes.rb
Rails.application.routes.draw do
  delete '/logout', to: 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#auth_failure'
  get '/admin-login', to: 'sessions#new'
  post '/admin-login', to: 'sessions#create_standard'
  get '/admin-logout', to: 'sessions#delete'
  delete "/admin-logout", to: "sessions#destroy"

  namespace :admin do
    get 'imports/import'
  end

  get '/sitemap.xml.gz', to: redirect("https://#{ENV['S3_BUCKET_NAME']}.s3.amazonaws.com/sitemaps/sitemap.xml.gz"), as: :sitemap
  root "welcome#index"

  get '/credit-card-beginners-guide', to: 'pages#start_here'
  get '/what-is-a-credit-score', to: 'pages#what_is_a_credit_score'
  get '/types-of-credit-cards', to: 'pages#types_of_credit_cards'
  get '/the-credit-card-game', to: 'pages#the_credit_card_game'

  resources :about, only: [:index]
  resources :users, only: [:show, :update, :edit, :destroy]
  resources :cards, only: [:index, :show]
  resources :blogs, only: [:index, :show]

  resources :categories, only: [:index]
  get "categories/:id", to: redirect("/%{id}")
  resources :categories, path: "", only: [:show]

  namespace :admin do
    get 'imports/index'
    resources :cards, only: [:new, :create, :edit, :update, :index]
    resources :rewards, only: [:new, :create, :edit, :update, :index, :destroy]
    resources :blogs
    resources :main_programs
    resources :card_programs
    resources :transfer_partners
    resources :imports do
      collection { post :import}
    end
  end

  namespace :api do
    namespace :v1, defaults: {format: :json} do
      get "/search", to: 'auto_complete#search'
      resources :rewards, only: [:show]
      get "/reward/:id", to: 'rewards#show_one'
      resources :categories, only: [:show]
      resources :favorite_cards
      resources :users, only: [:show]
      resources :cards, only: [:index]
      get 'card_names', to: 'cards#card_names'
      resources :blogs, only: [:index, :show]
      resources :related_blogs, only: [:show]
      resources :recent_blogs, only: [:index]
      resources :transfer_partners, only: [:show]
      get "/show_related_blogs/:id", to: "related_blogs#show_related_blogs"
    end
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController

  def index
    @linked_card = Card.find_by(name: "Chase Sapphire Preferred® Card")
    @best_cards  = Category.find_by(name: "best-credit-card-offers")
  end
end

app/views/about/_index_header.html.erb
<% provide(:title, "About") %>
<% provide(:meta_description, "Too Many Miles is dedicated to helping people maximize their credit card travel miles by finding them the best credit card sign up bonuses.") %>

app/views/about/index.html.erb
<%= render partial: "index_header" %>
<!-- Page Content -->
<div class="container">
<!-- Page Heading/Breadcrumbs -->
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">About
        <small>Too Many Miles</small>
      </h1>
    </div>
  </div>
<!-- /.row -->

<!-- Intro Content -->
  <div class="row">
    <div class="col-md-6">
      <%= image_tag("about/world.png", class: "img-responsive world-map") %><br>
      <h5 class="photo-tag"><strong>My world trip 2 years ago</strong></h5>
      <br>
    </div>
    <div class="col-md-6">
      <h2>Why Me?</h2>

      <p> <a href="http://www.sweatersaga.com/" class="active">Two years ago</a>, I traveled completely around the world for free. How? By strategically applying for travel credit cards and using the points I earned to pay for flights.  In total, I took 13 flights without spending any real cash.  I want to share what I learned, so that you, too, can explore the world without breaking the bank.</p>

      <h2>Why Too Many Miles?</h2>

      <p>Travel credit cards offer excellent sign up bonuses. For example, the <%= link_to @linked_card.name, card_path(@linked_card), class: "active" %>, is currently offering <%= number_with_delimiter(@linked_card.rewards.first.amount) %> points if you spend <%= number_to_currency(@linked_card.rewards.first.spending_amount, precision: 0) %> in <%= pluralize(@linked_card.rewards.first.length_of_time, "month") %>. These points can be converted to airline miles and offer you a chance to see the world for free. In this case, Chase is giving away approximately $625 in flights!</p>

      <p><strong>The problem? These sign up bonuses are fleeting.</strong> Some months, the deals are better than others, and the best deals can disappear quickly. Our app tracks bonuses across a variety of cards and <%= link_to "provides recommendations", category_path(@best_cards), class: "active" %> based on the cards' current offers relative to their historical offers. We will coach you to apply at the correct time, and receive the largest bonus possible!</p>
    </div>
  </div>
 <!-- /.row -->

        <!-- Team Members -->
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header" id="our-team">Our Team</h1><br>
    </div>
    <div class="col-md-offset-3 col-md-6 text-center">
      <div class="thumbnail team-member">
        <%= image_tag("about/bret.jpg", class: "img-responsive") %>
        <div class="caption">
          <h3>Bret Doucette<br>
            <small>Founder &amp; Developer</small>
          </h3>
          <p><strong>"Travel Addict, Lord of the Rings Enthusiast, and Web Developer."</strong></p>
          <p>Bret graduated from the University of Virginia in 2010, attended business school at Wake Forest, and worked in finance in Washington D.C. until realizing his heart wasn’t in it. Bret quit his job in 2014 to travel the world for 4 months.  Among many valuable life lessons, Bret acquired a vast knowledge of the credit card game during his trip. Currently Bret lives in Denver, CO and spends his days working in software consulting. His nights are spent working on Too Many Miles where he hopes to share what he learned so you can travel more for less!</p>
            <ul class="list-inline">
              <li><a href="https://www.facebook.com/profile.php?id=1526930"><i class="soap-icon-facebook"></i></a></li>
              <li><a href="https://www.linkedin.com/in/bretdoucette"><i class="soap-icon-linkedin"></i></a></li>
              <li><a href="https://twitter.com/bretdou"><i class="soap-icon-twitter"></i></a></li>
            </ul>
          </div>
        </div><br>
    </div>
    <div class="col-md-offset-3 col-md-6 text-center">
      <div class="thumbnail team-member">
        <%= image_tag("about/blake.jpg", class: "img-responsive") %>
        <div class="caption">
          <h3>Blake Thomas<br>
            <small>Developer &amp; Card Strategist</small>
          </h3>
          <p><strong>"Snow Skier, Blitz Patzer, and Data Visualizer"</strong></p>
          <p>Following his graduation from the University of Virginia in 2010, Blake worked in Charlottesville, Virginia as a neurological researcher. He currently resides in Washington, D.C. and works as a consultant, writing JavaScript to create complex data visualizations for the policy industry. A passionate credit card enthusiast, Blake uses his knowledge to provide content and information for our (soon to be) blogs and codes graphs to help you visualize the best deals!</p>
          <ul class="list-inline">
            <li><a href="https://www.facebook.com/profile.php?id=1526013"><i class="soap-icon-facebook"></i></a></li>
            <li><a href="https://www.linkedin.com/in/blake-thomas-63177987"><i class="soap-icon-linkedin"></i></a></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="col-md-offset-3 col-md-6 text-center">
      <div class="thumbnail team-member">
        <%= image_tag("about/mike.jpg", class: "img-responsive") %>
        <div class="caption">
          <h3>Michael Craigmile<br>
            <small>Card Strategist &amp; Content Editor</small>
          </h3>
          <p><strong>"Outdoorsman, History Buff, Political Junkie"</strong></p>
          <p>Mike graduated from the University of Virginia in 2012 where he studied history and foreign affairs. After graduation he was based in Chicago for a year and a half working in the nuclear industry traveling all over America as well as China, Korea, Taiwan, and Japan. He currently resides in Alexandria, Virginia and consults on energy policy and regulation for a DC-based public and government affairs firm. A vehement believer and practitioner of credit card rewards programs, Mike researches and writes blogs on current deals and how best to apply them. He also manages Too Many Miles' social media platforms.</p>
          <ul class="list-inline">
            <li><a href="https://www.facebook.com/mcraigmile7"><i class="soap-icon-facebook"></i></a></li>
            <li><a href="https://www.linkedin.com/in/michael-craigmile-a8551635"><i class="soap-icon-linkedin"></i></a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <!-- /.row -->
  <!-- Our Customers -->
  <hr>
</div>