config/routes.rb
Rails.application.routes.draw do
  delete '/logout', to: 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#auth_failure'
  get '/admin-login', to: 'sessions#new'
  post '/admin-login', to: 'sessions#create_standard'
  get '/admin-logout', to: 'sessions#delete'
  delete "/admin-logout", to: "sessions#destroy"

  namespace :admin do
    get 'imports/import'
  end

  get '/sitemap.xml.gz', to: redirect("https://#{ENV['S3_BUCKET_NAME']}.s3.amazonaws.com/sitemaps/sitemap.xml.gz"), as: :sitemap
  root "welcome#index"

  get '/credit-card-beginners-guide', to: 'pages#start_here'
  get '/what-is-a-credit-score', to: 'pages#what_is_a_credit_score'
  get '/types-of-credit-cards', to: 'pages#types_of_credit_cards'
  get '/the-credit-card-game', to: 'pages#the_credit_card_game'

  resources :about, only: [:index]
  resources :users, only: [:show, :update, :edit, :destroy]
  resources :cards, only: [:index, :show]
  resources :blogs, only: [:index, :show]

  resources :categories, only: [:index]
  get "categories/:id", to: redirect("/%{id}")
  resources :categories, path: "", only: [:show]

  namespace :admin do
    get 'imports/index'
    resources :cards, only: [:new, :create, :edit, :update, :index]
    resources :rewards, only: [:new, :create, :edit, :update, :index, :destroy]
    resources :blogs
    resources :main_programs
    resources :card_programs
    resources :transfer_partners
    resources :imports do
      collection { post :import}
    end
  end

  namespace :api do
    namespace :v1, defaults: {format: :json} do
      get "/search", to: 'auto_complete#search'
      resources :rewards, only: [:show]
      get "/reward/:id", to: 'rewards#show_one'
      resources :categories, only: [:show]
      resources :favorite_cards
      resources :users, only: [:show]
      resources :cards, only: [:index]
      get 'card_names', to: 'cards#card_names'
      resources :blogs, only: [:index, :show]
      resources :related_blogs, only: [:show]
      resources :recent_blogs, only: [:index]
      resources :transfer_partners, only: [:show]
      get "/show_related_blogs/:id", to: "related_blogs#show_related_blogs"
    end
  end
end

app/models/main_program.rb
class MainProgram < ActiveRecord::Base
  has_many :main_program_card_programs
  has_many :card_programs, through: :main_program_card_programs

  validates :name,
    presence: true,
    uniqueness: true
end

app/controllers/admin/main_programs_controller.rb
class Admin::MainProgramsController < Admin::BaseController
  before_action :load_main_program, only: [:edit, :update]
  before_action :format_card_programs_ids, only: [:create, :update]

  def index
    @main_programs = MainProgram.all.order('created_at DESC')
  end

  def new
    @main_program = MainProgram.new
  end

  def create
    @main_program = MainProgram.new(main_program_params.except(:card_programs))
    if @main_program.save
      assign_card_programs_to_main_programs(format_card_programs_ids)
      redirect_to admin_main_programs_path
    else
      flash.now[:errors] = main_program.errors.full_messages.join(", ")
      render :new
    end
  end

  def edit
  end

  def update
    if @main_program.update(main_program_params.except(:card_programs))
      assign_card_programs_to_main_programs(format_card_programs_ids)
      flash[:success] = "Main program successfully updated!"
      redirect_to admin_main_programs_path
    else
      flash.now[:errors] = main_program.errors.full_messages.join(", ")
      render :edit
    end
  end

  private

    def format_card_programs_ids
      @_selected_card_programs ||= main_program_params[:card_programs].reject!{|p| p == ""}
    end

    def assign_card_programs_to_main_programs(selected_card_programs)
      selected_card_programs.each do |id|
        card_program = CardProgram.find(id)
        if !program_not_already_assigned(card_program)
          @main_program.card_programs << card_program
        end
      end
    end

    def program_not_already_assigned(card_program)
      @main_program.card_programs.include?(card_program)
    end


    def main_program_params
      params.require(:main_program).permit(:id,
                                           :name,
                                           :image_url,
                                           card_programs: [])
    end

    def load_main_program
      @main_program ||= MainProgram.find(params[:id])
    end
end

app/helpers/admin/main_programs_helper.rb
module Admin::MainProgramsHelper
end

app/views/admin/main_programs/_form.html.erb
<%= bootstrap_form_for([:admin, @main_program]) do |program| %>
  <%= program.hidden_field :id, value: @main_program.id %>
  <%= program.text_field :name %>
  <%= program.text_field :image_url %>
  <%= program.collection_select :card_programs, CardProgram.order(:name),:id,:name, {:include_blank => false}, {:multiple => true} %>
  <%= program.submit 'Submit Information' %>
<% end %>
<%= link_to "Go Back to Main Admin Panel",  admin_cards_path %>

app/views/admin/main_programs/edit.html.erb
<div class="container upload-file">
  <div class="row">
    <div class="col-lg-12">
      <%= bootstrap_form_for([:admin, @main_program]) do |program| %>
        <%= program.hidden_field :id, value: @main_program.id %>
        <%= program.text_field :name %>
        <%= program.text_field :image_url %>
        <%= program.collection_select :card_programs, CardProgram.order(:name),:id,:name, {:include_blank => false}, {:multiple => true} %>
        <%= program.submit 'Submit Information' %>
      <% end %>
      <%= link_to "Go Back to Main Admin Panel",  admin_cards_path %>
    </div>
  </div>
</div>

app/views/admin/main_programs/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h2>Too Many Miles - Main Programs</h2><br>
      <ul>
        <% @main_programs.each do |program| %>
          <li><%= program.name %> | <%= link_to "Edit", edit_admin_main_program_path(program) %></li>
        <% end %>
      </ul><br>
      </br></br>
      <h3><%= link_to "Create a New Main Program", new_admin_main_program_path %></h3>
      <h3><%= link_to "Go Back to Main Admin Panel", admin_cards_path %></h3>
    </div>
  </div>
</div>

app/views/admin/main_programs/new.html.erb
<div class="container upload-file">
  <div class="row">
    <div class="col-lg-12">
      <%= render partial: 'form', :locals => {:main_program => @main_program} %>
    </div>
  </div>
</div>